on:
  release:
    types: [published]

name: Publish binaries to release

jobs:
  publish-crates-io:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Login
        run: cargo login ${{ secrets.CRATES_TOKEN }}
      - name: Publish the internal derive crate
        run: |-
          cd derive
          cargo publish
      - name: Publish deserr to crates.io
        run: cargo publish
